### ISSUE TITLE
`cargo espflash flash` fails on OSX 

### ISSUE THREAD

**Issue by rabarar** [gerardcl/esp32-c3-rust-std#1]
OSX using `brew` for `python` fails even with `virtualenv` installed (with brew) as it isn't an importable module and can't be easily added. The solution is to modify the script to work within a virtual environment or not to use `import virtualenv`

```
 % cargo espflash flash --release
[2024-12-28T19:07:04Z INFO ] Detected 2 serial ports
[2024-12-28T19:07:04Z INFO ] Ports which match a known common dev board are highlighted
[2024-12-28T19:07:04Z INFO ] Please select a port
[2024-12-28T19:07:05Z INFO ] Serial port: '/dev/cu.usbmodem5101'
[2024-12-28T19:07:05Z INFO ] Connecting...
[2024-12-28T19:07:05Z INFO ] Using flash stub
   Compiling esp-idf-sys v0.32.1
error: failed to run custom build command for `esp-idf-sys v0.32.1`

Caused by:
  process didn't exit successfully: `/Users/robert/src/rust/esp32-c3-rust-std/target/release/build/esp-idf-sys-92ded64f54805588/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=ESP_IDF_TOOLS_INSTALL_DIR
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG_DEFAULTS
  cargo:rerun-if-env-changed=MCU
  cargo:rerun-if-env-changed=ESP_IDF_SYS_ROOT_CRATE
  cargo:rerun-if-env-changed=ESP_IDF_VERSION
  cargo:rerun-if-env-changed=ESP_IDF_REPOSITORY
  cargo:rerun-if-env-changed=ESP_IDF_CMAKE_GENERATOR
  cargo:rerun-if-env-changed=IDF_PATH
  cargo:rerun-if-env-changed=EXTRA-COMPONENTS
  cargo:rerun-if-env-changed=ESP_IDF_COMPONENTS
  ESP_IDF_VERSION=4.4
  PATH=/Users/robert/src/rust/esp32-c3-rust-std/.embuild/espressif/esp-idf/release-v4.4/tools:$PATH
  pip 24.3.1 from /opt/homebrew/lib/python3.13/site-packages/pip (python 3.13)
  Creating a new Python environment in /Users/robert/src/rust/esp32-c3-rust-std/.embuild/espressif/python_env/idf4.4_py3.13_env

  --- stderr
  Build configuration: BuildConfig {
      esp_idf_tools_install_dir: None,
      esp_idf_sdkconfig: None,
      esp_idf_sdkconfig_defaults: None,
      mcu: None,
      native: NativeConfig {
          esp_idf_version: Some(
              Branch(
                  "release/v4.4",
              ),
          ),
          esp_idf_repository: None,
          esp_idf_cmake_generator: None,
          idf_path: None,
          extra_components: [],
          esp_idf_components: None,
      },
      esp_idf_sys_root_crate: None,
  }
  Using managed esp-idf repository: RemoteSdk { repo_url: None, git_ref: Branch("release/v4.4") }
  usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear]
              [--upgrade] [--without-pip] [--prompt PROMPT] [--upgrade-deps]
              [--without-scm-ignore-files]
              ENV_DIR [ENV_DIR ...]
  venv: error: unrecognized arguments: --python --seeder pip /Users/robert/src/rust/esp32-c3-rust-std/.embuild/espressif/python_env/idf4.4_py3.13_env
  Traceback (most recent call last):
    File "/Users/robert/src/rust/esp32-c3-rust-std/.embuild/espressif/esp-idf/release-v4.4/tools/idf_tools.py", line 1996, in <module>
      main(sys.argv[1:])
      ~~~~^^^^^^^^^^^^^^
    File "/Users/robert/src/rust/esp32-c3-rust-std/.embuild/espressif/esp-idf/release-v4.4/tools/idf_tools.py", line 1992, in main
      action_func(args)
      ~~~~~~~~~~~^^^^^^
    File "/Users/robert/src/rust/esp32-c3-rust-std/.embuild/espressif/esp-idf/release-v4.4/tools/idf_tools.py", line 1618, in action_install_python_env
      subprocess.check_call([sys.executable, '-m', 'venv',
      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             *virtualenv_options,
                             ^^^^^^^^^^^^^^^^^^^^
                             idf_python_env_path],
                             ^^^^^^^^^^^^^^^^^^^^^
                            stdout=sys.stdout, stderr=sys.stderr,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            env=env_copy)
                            ^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 419, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/opt/homebrew/opt/python@3.13/bin/python3.13', '-m', 'venv', '--python', '/opt/homebrew/opt/python@3.13/bin/python3.13', '--seeder', 'pip', '/Users/robert/src/rust/esp32-c3-rust-std/.embuild/espressif/python_env/idf4.4_py3.13_env']' returned non-zero exit status 2.
  Error: Could not install esp-idf

  Caused by:
      command 'env -u IDF_PYTHON_ENV_PATH -u MSYSTEM IDF_TOOLS_PATH="/Users/robert/src/rust/esp32-c3-rust-std/.embuild/espressif" "python3" "/Users/robert/src/rust/esp32-c3-rust-std/.embuild/espressif/esp-idf/release-v4.4/tools/idf_tools.py" "--idf-path" "/Users/robert/src/rust/esp32-c3-rust-std/.embuild/espressif/esp-idf/release-v4.4" "--non-interactive" "install-python-env"' exited with non-zero status code 1
```

**Comment by gerardcl** [comment]
did you try checking latest official docs?

**Comment by rabarar** [comment]
Any specific section you’d care to point me towards?On Jan 18, 2025, at 8:29 AM, gerardcl ***@***.***> wrote:﻿
did you try checking latest official docs?

**Comment by gerardcl** [comment]
In the readme of this repo there are all the links I used to get this working, this is long time ago, I can't help more here as I am not using OSX for embedded topics but I believe there shouldn't be too much difference on OSX, maybe try using pyenv to setup the python env globally because it might seem an issue on permissions and you don't want that to be on sudo all time. Nevertheless, since by the time I published this repo there are for sure a lot of updates on the tooling please make sure reading their docs and do not rely on this repo too much.
